repos:
-   repo: https://github.com/ambv/black
    rev: 21.9b0
    hooks:
    - id: black
      language_version: python3
      files: ^src/

-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
      files: ^src/

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910-1
    hooks:
    - id: mypy
      files: ^src/
