repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3
      files: ^src/

-   repo: https://gitlab.com/pycqa/flake8
    rev: master
    hooks:
    - id: flake8
      files: ^src/

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: master
    hooks:
    - id: mypy
      files: ^src/
