name: Build and package

on:
  push:
    tags:
      - 'v*.*.*'

  workflow_dispatch:

  schedule:
    - cron: "19 3 * * *" # everyday at 03:19

jobs:
  build_macos:
    runs-on: macos-11.0
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.merged.sha }}

      - name: Import signing certificate into keychain
        uses: apple-actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.SIGNING_CERTIFICATE_P12_DATA }}
          p12-password: ${{ secrets.SIGNING_CERTIFICATE_PASSWORD }}

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install --upgrade briefcase
          chmod +x ./scripts/post-build-macos.sh

      - name: Build app
        id: build
        run: |
          # build app
          briefcase build macOS Xcode

          # run post-build scripts:
          # - add CLI executable
          # - keep .pyc files only to save space
          # - update plist entries
          APP_PATH=$( find . -name "*.app" )
          ./scripts/post-build-macos.sh $APP_PATH

          # package dmg
          briefcase package macOS Xcode -i "$DEV_ID"

          DMG_PATH=$( find . -name "*.dmg" )
          DMG_NAME=$( basename "$DMG_PATH" )
          echo "dmg created: $DMG_PATH"
          echo "::set-output name=dmg_name::${DMG_NAME}"
          echo "::set-output name=dmg_path::${DMG_PATH}"
        env:
            DEV_ID: "Developer ID Application: Sam Schott (G34LNR8C4Y)"

      - name: Notarize app
        run: |
          npx notarize-cli --bundle-id "com.samschott.maestral" \
                           --file ${{ steps.build.outputs.dmg_path }}
        env:
          NOTARIZE_USERNAME: ${{ secrets.NOTARIZE_USERNAME }}
          NOTARIZE_PASSWORD: ${{ secrets.NOTARIZE_PASSWORD }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.build.outputs.dmg_name }}
          path: ${{ steps.build.outputs.dmg_path }}
