name: Build and package

on:
  push:
    tags:
      - "v*.*.*"

  workflow_dispatch:

jobs:
  build_macos:
    runs-on: macos-11
    name: Build app bundle
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Import signing certificate into keychain
        uses: apple-actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.SIGNING_CERTIFICATE_P12_DATA }}
          p12-password: ${{ secrets.SIGNING_CERTIFICATE_PASSWORD }}

      - name: Set up Python
        run: |
          wget -q https://www.python.org/ftp/python/3.9.9/python-3.9.9-macos11.pkg
          sudo installer -pkg python-3.9.9-macos11.pkg -target /
          python3 -c "import sys; print(sys.version)"
          echo "/Library/Frameworks/Python.framework/Versions/3.9/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          python3 -m pip install -U pip
          python3 -m pip install -U briefcase
          chmod +x ./scripts/post-build-macos.sh

      - name: Bump build number
        run: |
          cd macOS/Xcode/Maestral
          agvtool next-version -all

      - name: Build app
        id: build
        run: |
          
          # remove old dist-info from app bundle, see briefcase issue #644
          find "macOS/Xcode/Maestral/Maestral/app" -name "*.dist-info"  -prune -exec rm -rf {} \;
          find "macOS/Xcode/Maestral/Maestral/app_packages" -name "*.dist-info"  -prune -exec rm -rf {} \;

          # update Python code
          briefcase update macOS Xcode -r -d

          # build app
          briefcase build macOS Xcode

          # run post-build scripts:
          # - add CLI executable
          # - keep .pyc files only to save space
          APP_PATH=$( find . -name "*Maestral.app" | head -n 1)
          ./scripts/post-build-macos.sh $APP_PATH

          # package as dmg
          briefcase package macOS Xcode -i "$DEV_ID"

          # prepare output for notarization step
          DMG_PATH=$( find . -name "*.dmg" )
          DMG_NAME=$( basename "$DMG_PATH" )
          echo "dmg created: $DMG_PATH"
          echo "::set-output name=dmg_name::${DMG_NAME}"
          echo "::set-output name=dmg_path::${DMG_PATH}"
        env:
            DEV_ID: "Developer ID Application: Sam Schott (G34LNR8C4Y)"
            PIP_NO_BINARY: "watchdog"

      - name: Notarize app
        run: |
          npx notarize-cli --bundle-id "com.samschott.maestral" \
                           --file ${{ steps.build.outputs.dmg_path }}
        env:
          NOTARIZE_USERNAME: ${{ secrets.NOTARIZE_USERNAME }}
          NOTARIZE_PASSWORD: ${{ secrets.NOTARIZE_PASSWORD }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.build.outputs.dmg_name }}
          path: ${{ steps.build.outputs.dmg_path }}

      - name: Push back Xcode project updates
        uses: stefanzweifel/git-auto-commit-action@v4
        if: github.ref == 'refs/heads/master'
        with:
          commit_message: Auto-commit build updates
