name: Build and package

on:
  push:
    tags:
      - "v*.*.*"

  workflow_dispatch:

jobs:
  build_macos:
    runs-on: macos-11
    name: Build app bundle
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Import signing certificate into keychain
        uses: apple-actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.SIGNING_CERTIFICATE_P12_DATA }}
          p12-password: ${{ secrets.SIGNING_CERTIFICATE_PASSWORD }}

      - name: Set up Python
        run: |
          wget -q https://www.python.org/ftp/python/3.10.4/python-3.10.4-macos11.pkg
          sudo installer -pkg python-3.10.4-macos11.pkg -target /
          python3 -c "import sys; print(sys.version)"
          echo "/Library/Frameworks/Python.framework/Versions/3.10/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          python3 -m pip install -U pip
          python3 -m pip install -U briefcase
          python3 -m pip install -U bump2version
          python3 -m pip install "markupsafe<2.1"  # needed until next briefcase release
          chmod +x ./scripts/post-build-macos.sh

      - name: Bump build number
        run: |
          bump2version major --config-file .bumpversion-build.cfg

      - name: Build app
        id: build
        run: |

          # Recreate Xcode project. This is currently required to update project metadata,
          # see https://github.com/beeware/briefcase/issues/472.
          rm -Rf macOS/Xcode
          briefcase create macOS Xcode --no-input

          # build app
          briefcase build macOS Xcode --no-input

          # run post-build scripts:
          # - add CLI executable
          # - keep .pyc files only to save space
          APP_PATH=$( find . -name "*Maestral.app" | head -n 1)
          ./scripts/post-build-macos.sh $APP_PATH

          # package as dmg
          briefcase package macOS Xcode -i "$DEV_ID" --no-input

          # prepare output for notarization step
          DMG_PATH=$( find . -name "*.dmg" )
          DMG_NAME=$( basename "$DMG_PATH" )
          echo "dmg created: $DMG_PATH"
          echo "::set-output name=dmg_name::${DMG_NAME}"
          echo "::set-output name=dmg_path::${DMG_PATH}"
        env:
            DEV_ID: "Developer ID Application: Sam Schott (G34LNR8C4Y)"
            PIP_NO_BINARY: "watchdog"

      - name: Notarize app
        run: |
          npx notarize-cli --bundle-id "com.samschott.maestral" \
                           --file ${{ steps.build.outputs.dmg_path }}
        env:
          NOTARIZE_USERNAME: ${{ secrets.NOTARIZE_USERNAME }}
          NOTARIZE_PASSWORD: ${{ secrets.NOTARIZE_PASSWORD }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.build.outputs.dmg_name }}
          path: ${{ steps.build.outputs.dmg_path }}

      - name: Push back Xcode project updates
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Auto-commit build updates
